name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go-version: [ oldstable, stable ]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check and get dependencies
      run: |
        go mod tidy
        git diff --exit-code go.mod
        git diff --exit-code go.sum

    - name: Build binary
      run: go build -v ./cmd/unnecessaryerror